### ISSUE TITLE
Different asset paths on Windows vs other platforms?

### ISSUE THREAD

**Issue by hexbloom** [DanB91/Zig-Playdate-Template#11]
When I run the project on my Windows machine, this fails loading the image:

`const playdate_image = playdate.graphics.loadBitmap("images/playdate_image", null).?;`

On Windows, `build.zig` copies the assets into an `assets` folder inside the `.pdx` folder, and inside that is the `images` folder. To fix this issue, you can instead copy the `assets` folder directly into the `.pdx` by changing to this line in `build.zig`:

`try addCopyDirectory(writer, "assets", ".");`

Since I don't have a Mac, I'm not sure of the best cross-platform way to resolve this issue... maybe with some collaboration we could work this one out?

**Comment by DanB91** [comment]
Ah crap that is my fault.  I accidentally broke the template with my last commit.  It's supposed to be `"assets/images/playdate_image"`   Just pushed a fix. Please pull the latest and let me know if that fixes things.

Thanks for pointing this out!

**Comment by hexbloom** [comment]
Works, ty! Take a look at my other PR which fixes Windows compilation, too.
