### ISSUE TITLE
Support Zig Compiler version 0.12.0-dev

### ISSUE THREAD

**Issue by DavidMedin** [DanB91/Zig-Playdate-Template#8]
I recently upgraded my Zig version to master, which is 0.12.0-dev.2036+fc79b22a9. I had to make a few changes to the `build.zig` to get it to build. The sample project works on the Playdate Simulator, but crashes on the device.
Here is a crash log from it:
```
--- crash at 2024/01/05 06:46:53---
build:712beb42-2.1.1-release.161138-buildbot
   r0:240f0074    r1:00000000     r2:00000000    r3: 90000000
  r12:00000001    lr:24053585     pc:90000000   psr: 80070000
 cfsr:00020000  hfsr:40000000  mmfar:00000000  bfar: 00000000
rcccsr:00000000
heap allocated: 420768
Lua totalbytes=0 GCdebt=0 GCestimate=0 stacksize=0
```

It is possible that the Zig compiler is at fault in the current build I have. But it could be the `build.zig` file.

**Comment by DanB91** [comment]
Got it working.  Looks like some recent-ish changes in Zig changed the ELF layout that doesn't play well with what PDC expects.  Changes incoming...

**Comment by DanB91** [comment]
@DavidMedin just pushed the fix.  Please pull the latest and let me know if it works.

**Comment by DavidMedin** [comment]
At the moment it doesn't build. The error suggests that the Dir variable below doesn't have iteration permission.
https://github.com/DanB91/Zig-Playdate-Template/blob/765e535d1c98034e7e688a6d3dff78fd6b3998c2/build.zig#L87
So, I changed it to the code below. It now builds and doesn't crash on the Playdate device.
```zig
var dir = try b.build_root.handle.openDir(src_path, .{ .iterate = true });
```
Thank you for the changes!

**Comment by DanB91** [comment]
Ah interesting that this worked fine on macOS. I just pushed a change to add the iterate flag, since that's all that was needed to fix it on your side.  Thanks for bring this to my attention!
